[package]
name = "gnome-search-providers-jetbrains"
description = "Gnome search providers for recent projects from Jetbrains IDEs"
readme = "README.md"
homepage = "https://github.com/lunaryorn/gnome-search-providers-jetbrains"
repository = "https://github.com/lunaryorn/gnome-search-providers-jetbrains"
version = "1.4.1"
license = "MPL-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"
# We don't publish this to crates.io; you can't install it with cargo install
# because you'd miss the required service and configuration files, and you
# wouldn't want to depend on it either.
publish = false

[dependencies]
gio = "^0.9"
globwalk = "^0.8"
regex = "^1.4"
lazy_static = "^1.4"
dirs = "3.0.1"
elementtree = "^0.5"
anyhow = "^1.0"
env_logger = "^0.8"
log = "^0.4"
clap = { version = "^2.33", default-features = false }
gnome-search-provider-common = { path = "./crates/common" }
systemd = "^0.8"

[dev-dependencies]
pretty_assertions = "^0.7"
rust-ini = "^0.17"

[workspace]
members = ["./crates/common"]
