[package]
name = "gnome-search-provider-common"
description = "Common code for Gnome search providers"
version = "0.1.0"
homepage = "https://github.com/lunaryorn/gnome-search-providers-jetbrains"
repository = "https://github.com/lunaryorn/gnome-search-providers-jetbrains"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"
license = "MPL-2.0"
# We don't publish this to crates.io; because it's purely used for my search providers as git dependency.
publish = false

[dependencies]
indexmap = "^1.6"
zbus = "2.0.0-beta.3"
thiserror = "^1.0"
gio = "^0.9"
glib = "^0.10"
libc = "^0.2"
slog = "^2.7"
slog-journald = "^2.1"
slog-term = "^2.8"
slog-stdlog = "^4.1"
slog-scope = "^4.4"
slog-envlogger = { version = "^2.2", default-features = false }

[dev-dependencies]
pretty_assertions = "^0.7"